---
events:
  - death
num_durations: 256
cuda: cuda:3
seed: 1111 # null for random seed
load_data:
  features_before_preprocessing:
    - gender
    - age_calculated
    - Creatinine
    - Hemoglobin
    - eGFR
    - UPCR
    - ACUR
  path: Data/TrainingData/SyntheticData/dummy_timeseries_data.csv

model:
  layers_for_attention:
    - 8
    - 8
  layers_for_each_deephit_event:
    - 8
  layers_for_predicting_next_time_step:
    - 32
    - 32
  num_hidden: 8
  num_rnn_layers: 8
  rnn_type: LSTM
  dropout: 0.3

loss:
  use_constraints: false
  alpha: 0.01
  delta: 0.05
  beta: 0.01
  kappa: 0.1
  sigma: 0.01
  bound_dict:
    '2':
      - 1
      - 2
    '3':
      - 3
      - 4
    '4':
      - 1
      - 4
  gamma:
    - 0
    - 0
    - 0

training:
  learning_rate: 0.0001
  num_durations: 128
  num_epochs: 25
  batch_size: 64
  grad_clip: 0.9034919529397347
  weight_decay: 1e-3

lr_scheduler:
  mode: min    
  factor: 0.5    
  patience: 8
  threshold: 1e-3
  threshold_mode: abs
  min_lr: 3e-5

results:
  plots: true
  save_results: true
  comparison: null # WIP: dict of paths to comparable data

experiements:


